from django.urls import path, include
from .views import login_view, logout_view, dashboard_view, create_user_view, patient_detail_view, patient_list_view, patient_create_view, admit_patient_view, discharge_patient_view, available_bed_api, appointment_create_view, appointment_list_view, appointment_complete_view, appointment_cancel_view, emr_create_view, emr_update_view, emr_search_view, emr_pdf_view, assign_doctor_view, specializations_api, user_list_view, user_detail_view, user_toggle_active_view, lab_order_list_view, lab_order_detail_view, lab_order_create_view, lab_result_entry_view, lab_order_status_view, lab_testtype_list_view, lab_testtype_create_view, lab_testtype_delete_view, lab_testtype_edit_view, lab_order_pdf_view
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', dashboard_view, name='dashboard'),
    path('create-user/', create_user_view, name='create_user'),
    path('patients/', patient_list_view, name='patient_list'),
    path('patients/create/', patient_create_view, name='patient_create'),
    path('patients/<str:patient_id>/admit/', admit_patient_view, name='patient_admit'),
    path("patients/<str:patient_id>/assign_doctor/", assign_doctor_view, name="assign_doctor"),
    path('patients/<int:admission_id>/discharge/', discharge_patient_view, name='patient_discharge'),
    path('patients/<str:patient_id>/', patient_detail_view, name='patient_detail'),
    path("api/beds/available/", available_bed_api, name="available_beds_api"),
    path('appointments/create/', appointment_create_view, name='appointment_create'),
    path('appointments/', appointment_list_view, name='appointment_list'),
    path('appointments/<int:appointment_id>/complete/', appointment_complete_view, name='appointment_complete'),
    path('appointments/<int:appointment_id>/cancel/', appointment_cancel_view, name='appointment_cancel'),
    path("patients/<str:patient_id>/emr/create", emr_create_view, name="emr_create"),
    path("emr/search/", emr_search_view, name="emr_search"),
    path("emr/<int:emr_id>/edit/", emr_update_view, name="emr_edit"),
    path("emr/<int:emr_id>/pdf/", emr_pdf_view, name="emr_pdf"),
    path("api/specializations/", specializations_api, name="specializations_api"),
    path("users/", user_list_view, name="user_list"),
    path("users/<int:user_id>/", user_detail_view, name="user_detail"),
    path("users/<int:user_id>/toggle-active/", user_toggle_active_view, name="user_toggle_active"),
    path("lab/orders/", lab_order_list_view, name="lab_order_list"),
    path("lab/orders/<int:order_id>/", lab_order_detail_view, name="lab_order_detail"),
    path("patients/<str:patient_id>/lab/create/", lab_order_create_view, name="lab_order_create"),
    path("lab/orders/<int:order_id>/results/", lab_result_entry_view, name="lab_result_entry"),
    path("lab/orders/<int:order_id>/status.<str:status>/", lab_order_status_view, name="lab_order_status"),
    path("lab/tests/", lab_testtype_list_view, name="lab_testtype_list"),
    path("lab/tests/create/", lab_testtype_create_view, name="lab_testtype_create"),
    path("lab/tests/<int:test_id>/edit/", lab_testtype_edit_view, name="lab_testtype_edit"),
    path("lab/tests/<int:test_id>/delete/", lab_testtype_delete_view, name="lab_testtype_delete"),
    path("lab/orders/<int:order_id>/pdf/", lab_order_pdf_view, name="lab_order_pdf"),
]
