# Generated by Django 6.0.2 on 2026-02-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_ida',
            new_name='patient_id',
        ),
    ]
