# Generated by Django 6.0.2 on 2026-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bed_ward_admission_billing_cleared_admission_bed_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ADMITTED')), fields=('bed',), name='unique_active_admission_per_bed'),
        ),
    ]
