# Generated by Django 6.0.2 on 2026-02-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admission_unique_active_admission_per_bed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='admission',
            name='unique_active_admission_per_bed',
        ),
    ]
