# Generated by Django 6.0.2 on 2026-02-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('form', models.CharField(blank=True, max_length=60)),
                ('dose', models.CharField(blank=True, max_length=60)),
                ('frequency', models.CharField(blank=True, max_length=60)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('emr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.emr')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='accounts.emr')),
            ],
        ),
    ]
