# Generated by Django 6.0.2 on 2026-03-02 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_specialization_user_specialzation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialzation',
            new_name='specialization',
        ),
    ]
