# Generated by Django 6.0.2 on 2026-03-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_laborder_labtesttype_laborderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_icu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='on_ventilator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTION', 'Reception'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('HR', 'HR'), ('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant')], default='RECEPTION', max_length=20),
        ),
        migrations.CreateModel(
            name='WardTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_charge_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_icu', models.BooleanField(default=False)),
                ('icu_extra_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventilator_extra_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to='accounts.ward')),
            ],
        ),
    ]
