# Generated by Django 6.0.2 on 2026-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_billinginvoice_billinginvoiceitem_billingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
