# Generated by Django 6.0.2 on 2026-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_billinginvoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='icu_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='ventilator_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
