# Generated by Django 6.0.2 on 2026-03-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_laborderitem_result_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_charge', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='accounts.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
