# Generated by Django 6.0.2 on 2026-03-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_medicine_medicineusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admission')),
            ],
        ),
    ]
